name = "nbidal18"
version = "4.1.3-packwiz"
description = "Fabric 1.21.1 adventure modpack with automatic Prism updates"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b0b1438d711505a75bcacffbc1fef6ec4e4f7770ad47b05351e1022ab683f8c"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
