name = "nbidal18"
version = "4.3.2"
description = "Fabric 1.21.1 adventure modpack with automatic Prism updates"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa8e4369303614cf798be74670e5344444dd5787d59f939ee12dd793ee9c8a97"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
