#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Aug 08 21:08:26 CEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=
