#Naturalist server config. Set (mob)_removed=true to disable a mob.
alligator_removed=false
anglerfish_removed=false
ant_removed=false
bass_removed=false
bear_removed=false
bird_head_slow_falling=true
bird_removed=false
black_bear_removed=false
blobfish_removed=false
boar_removed=false
butterfly_removed=false
capybara_removed=false
catfish_removed=false
clam_removed=false
crab_removed=false
deer_removed=false
desert_scorpion_removed=false
dragonfly_removed=false
duck_removed=false
elephant_removed=false
firefly_removed=false
forest_fox_removed=false
forest_rabbit_removed=false
giant_isopod_removed=false
giraffe_removed=false
great_white_shark_removed=false
hedgehog_removed=false
hippo_removed=false
jellyfish_removed=false
jungle_scorpion_removed=false
komodo_dragon_removed=false
lion_removed=false
lizard_removed=false
mammoth_removed=false
mole_removed=false
ostrich_removed=false
parrot_flight=true
piranha_removed=false
rat_removed=false
ray_removed=false
remove_all_bugs=false
rhino_removed=false
snail_crushing=false
snail_removed=false
snake_removed=false
starfish_removed=false
tiger_removed=false
tortoise_removed=false
turkey_removed=false
vulture_removed=false
whale_removed=false
zebra_removed=false
