gamerule.tntExplosionDropDecay=true
gamerule.logAdminCommands=false
gamerule.sendCommandFeedback=false
gamerule.globalSoundEvents=false
gamerule.spawnRadius=100
gamerule.showDeathMessages=false
gamerule.commandBlockOutput=false
gamerule.spectatorsGenerateChunks=false
gamerule.announceAdvancements=false
gamerule.doInsomnia=false
gamerule.naturalRegeneration=false
gamerule.randomTickSpeed=1
gamerule.reducedDebugInfo=true
gamerule.moneyDropPercentage=0
