org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version=1.21.1
fabric_loader_version=0.19.3
fabric_api_version=0.116.7+1.21.1
bcc_version=21.1.8
skin_overrides_version=2.6.0+1.21.1
autohud_version=8.11+1.21.1-fabric
thermoo_version=4.7.1
immersive_aircraft_version=1.4.1+1.21.1
immersive_machinery_version=0.2.0+1.21.1
artifacts_version=13.1.0
sodium_extra_version=mc1.21.1-0.6.0+fabric

mod_version=1.1.11+1.21.1
maven_group=dev.nbidal18
archives_base_name=nbidal18-pack-compat
